image: oarteam/batsim:latest

build:
  stage: build
  script:
    - mkdir /builds/OAR/batsim/build
    - cd /builds/OAR/batsim/build
    - cmake .. -Dtreat_warnings_as_errors=ON
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - /builds/OAR/batsim/

test:
  stage: test
  script:
    # Let's run the redis server
    - |
      redis-server>/dev/null &
      while ! nc -z localhost 6379; do
        sleep 1
      done

    - cd /builds/OAR/batsim/build
    - ctest -E smpi
  dependencies:
    - build
  artifacts:
    paths:
      - /builds/OAR/batsim/build/Testing
      - /tmp/batsim_tools_tests
      - /tmp/batsim_tests
