image: oarteam/batsim_ci

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - build
  - update_dependencies_cache
  - test
  - deploy

###############################################################################
# Build stage
###############################################################################
build:
  stage: build
  script:
    - ./ci/build.bash
  artifacts:
    paths:
      - /builds/batsim/batsim/build

###############################################################################
# Dependencies cache stage
###############################################################################
update_dependencies_cache:
  stage: update_dependencies_cache
  script:
    - ./ci/update-dependencies-cache.bash

###############################################################################
# Test stage
###############################################################################
test_test:
  stage: test
  script:
    - ./ci/run-tests.bash
  dependencies:
    - build
  artifacts:
    paths:
      - /builds/batsim/batsim/doc/doxygen_doc/html

test_unittest:
  stage: test
  script:
    - ./ci/run-unittests.bash
  dependencies:
    - build

###############################################################################
# Deploy stage
###############################################################################
update_batsim_dev_cache:
  stage: deploy
  script:
    - ./ci/update-batsim_dev-cache.bash
  dependencies:
    - test_test
    - test_unittest

deploy_code_doc:
  stage: deploy
  script:
      # Pushes Batsim's code doc (doxygen) onto the gforge website.
      # SSH setup (do NOT run these commands on your machine)
      - eval $(ssh-agent -s)
      - ssh-add <(echo "$SSH_PRIVATE_KEY")
      - mkdir -p ~/.ssh
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
      # Finally push the code documentation on the gforge website
      - cd /builds/batsim/batsim/doc
      - rsync -rlgoDz --delete doxygen_doc/html/ mpoquet@scm.gforge.inria.fr:/home/groups/batsim/htdocs/batsim/doxygen
  dependencies:
    - test_test
  only:
    - master
