image: oarteam/batsim_ci:2018-11-07

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - big_stage
  - deploy

###############################################################################
# Build and test
###############################################################################
build_and_test:
  stage: big_stage
  script:
    # Clean nix build with various compilers
    - ./ci/nix-build-gcc-and-update-dependencies-cache.bash
    - ./ci/nix-build-clang-and-update-dependencies-cache.bash
    # Local build to get coverage results, etc.
    - ./ci/manual-build.bash
    # Tests
    - ./ci/run-unittests.bash
    - ./ci/run-tests.bash
  artifacts:
    paths:
      - /builds/batsim/batsim/doc/doxygen_doc/html

###############################################################################
# Deploy
###############################################################################
deploy_code_doc:
  stage: deploy
  script:
      # Pushes Batsim's code doc (doxygen) onto the gforge website.
      # SSH setup (do NOT run these commands on your machine)
      - eval $(ssh-agent -s)
      - ssh-add <(echo "$SSH_PRIVATE_KEY")
      - mkdir -p ~/.ssh
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
      # Finally push the code documentation on the gforge website
      - cd /builds/batsim/batsim/doc
      - rsync -rlgoDz --delete doxygen_doc/html/ mpoquet@scm.gforge.inria.fr:/home/groups/batsim/htdocs/batsim/doxygen
  dependencies:
    - build_and_test
  only:
    - master

###############################################################################
# Tutorials
###############################################################################
tuto_first_simulation-stable:
  stage: big_stage
  only:
    - schedules
  script:
    - cd docs/tuto-first-simulation
    - nix-shell --pure ./tuto-env.nix --command ${CI_PROJECT_DIR}/ci/list-store-paths-for-cachix.bash | cachix push batsim
    - nix-shell ./tuto-env.nix --command './run_simulation_manually.bash'
    - nix-shell ./tuto-env.nix --command './run_simulation_robin.bash'

tuto_first_simulation:
  stage: big_stage
  only:
    - schedules
  script:
    - cd docs/tuto-first-simulation
    - nix-shell --pure ./tuto-env-dev.nix --command ${CI_PROJECT_DIR}/ci/list-store-paths-for-cachix.bash | cachix push batsim
    - DO_NOT_CHECK_VERSION=1 nix-shell ./tuto-env-dev.nix --command './run_simulation_manually.bash'
    - DO_NOT_CHECK_VERSION=1 nix-shell ./tuto-env-dev.nix --command './run_simulation_robin.bash'
