image: oarteam/batsim_ci

# The before_script part above is done in order to push Batsim's code doc
# onto the gforge website.
# Information found on https://docs.gitlab.com/ee/ci/ssh_keys/README.html
before_script:
  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # For Docker builds disable host key checking. Be aware that by adding that
  # you are suspectible to man-in-the-middle attacks.
  # WARNING: Use this only with the Docker executor, if you use it with shell
  # you will overwrite your user's SSH config.
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'


build:
  stage: build
  script:
    - mkdir /builds/OAR/batsim/build
    - cd /builds/OAR/batsim/build
    - cmake .. -Dtreat_warnings_as_errors=ON
    - make -j$(nproc)
    - make install
    - this line has only been added to make the build crash !!
  artifacts:
    paths:
      - /builds/OAR/batsim/

doc:
  stage: test
  script:
    - cd /builds/OAR/batsim/doc
    - doxygen
    - cat doxygen_warnings.log
    # The next line fails if doxygen generated warnings
    - eval "[ $(wc -c doxygen_warnings.log | cut -d ' ' -f1) -eq 0 ]"
  artifacts:
    paths:
      - /builds/OAR/batsim/doc/doxygen_doc/html

test:
  stage: test
  script:
    # Let's run the redis server
    - |
      redis-server>/dev/null &
      while ! nc -z localhost 6379; do
        sleep 1
      done

    - cd /builds/OAR/batsim/build
    - make install
    - ctest -E smpi
  dependencies:
    - build

deploy_code_doc:
  stage: deploy
  script:
    - cd /builds/OAR/batsim/doc
    - rsync -rlgoDz --delete doxygen_doc/html/ mpoquet@scm.gforge.inria.fr:/home/groups/batsim/htdocs
  dependencies:
    - doc
