image: oarteam/batsim_ci

build:
  stage: build
  script:
    - mkdir /builds/OAR/batsim/build
    - cd /builds/OAR/batsim/build
    - cmake .. -Dtreat_warnings_as_errors=ON
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - /builds/OAR/batsim/

doc:
  stage: test
  script:
    - cd /builds/OAR/batsim/doc
    - doxygen
    - cat doxygen_warnings.log
    # The next line fails if doxygen generated warnings
    - eval "[ $(wc -c doxygen_warnings.log | cut -d ' ' -f1) -eq 0 ]"
  artifacts:
    paths:
      - /builds/OAR/batsim/doxygen_doc/html

test:
  stage: test
  script:
    # Let's run the redis server
    - |
      redis-server>/dev/null &
      while ! nc -z localhost 6379; do
        sleep 1
      done

    - cd /builds/OAR/batsim/build
    - make install
    - ctest -E smpi
  dependencies:
    - build
