# Dependencies
addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libboost-all-dev
      - doxygen
      - graphviz
env:
  global:
    secure: "ayxHlRpg3qX84ZkiLVd5s78/woUyNET99uNFviUzdDiQ9iUoaudYuu9uG9zi0RVfY0QRqESNwt8UPKTpM19M2HUqOoCYX4n865qhVkjMr2yRjK9u+HtdKZnoDRbT3o/ogSGxkctqMJmSQcgg8UdowwlAIEktIGMwk6dsAt4yYfLWABsLRulNr9SRUkTE6eNdheQaBpdD7BgIwzkEJ5cHFrd8Z9s+yRdX2RG2uXjQ3JmxdfVS2w4sboSurCQyjhbZ198Pt0/gTToinxD/BxR4rS/xyHy1o4JRbeuY103iOqGXqL1ZmoapTEA0dJ4/S51qC+xFj2KbOj555mTFG/ubWKA3FG6lezYsWlwTFPJgCQPmMu4B3dW+8ASri9aDtFs9Zt7Ul6VcE/znu/PVUPgAZTvAntb9ZYn7LK801nhIc4AAJ5mAxr1qVhtJ05QxuC6vU4c4F8mhi4YlaMDQTk4/5U0I1btn1rR7sgz9yiiEvBBV6Dha7UrDOOqoN6eXL9KE5atUcsuN/kieejj46KmLzJcl4eoElxyb2pJj+LCLzwqoAjs/BLzNWGX1fLWO2xHUPB3tDP5m3PKp9aPv55KRXp/3H3wCHH9GxIzzA1oBX3Gb5GzoW3X1CInpeaNoqs6UqYuzUozl3068o4gdCypigh0OYDwpGzQXrWOhKMP8rdM="

sudo: required
dist: trusty

before_install:
  - export BATSIM_BASE_DIR=$(pwd)

  - cd travis # SSH setup for sharing the doxygen documentation
  - openssl aes-256-cbc -k "$ssh_key_password" -in travisci_rsa.enc -out travisci_rsa -d
  - chmod 0600 travisci_rsa
  - cp travisci_rsa ~/.ssh/id_rsa
  - ssh-keyscan scm.gforge.inria.fr >> ~/.ssh/known_hosts

install:
  - cd ${BATSIM_BASE_DIR} # Install SimGrid
  - git clone https://mpoquet@github.com/oar-team/simgrid-batsim.git -b batsim-compatible --depth 1 simgrid-batsim
  - cd simgrid-batsim
  - mkdir build
  - cd build
  - cmake .. -Denable_documentation=OFF
  - make -j $(nproc)
  - sudo make install

  - cd ${BATSIM_BASE_DIR} # Install rapidjson
  - git clone https://github.com/miloyip/rapidjson.git
  - cd rapidjson
  - git checkout 3d5848a # v1.02
  - sudo cp -a include/rapidjson /usr/include

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang

# Build steps
script:
  - cd ${BATSIM_BASE_DIR} # Compile Batsim
  - mkdir build
  - cd build
  - cmake ..
  - make -j $(nproc)

  - cd ${BATSIM_BASE_DIR}/doc # Doxygen documentation
  - doxygen
  - cat doxygen_warnings.log
  - eval "[ $(wc -c doxygen_warnings.log | cut -d ' ' -f1) -eq 0 ]" # Stops travis on doxygen warnings
  - rsync -rlgoDvz doxygen_doc/html/ mpoquet@scm.gforge.inria.fr:/home/groups/batsim/htdocs
