# Dependencies
addons:
  apt:
    packages:
      - cmake
      - doxygen
      - graphviz
      - python-pip
      - redis-server
      - libhiredis-dev
      - libev-dev
      - valgrind
env:
  global:
    secure: "ayxHlRpg3qX84ZkiLVd5s78/woUyNET99uNFviUzdDiQ9iUoaudYuu9uG9zi0RVfY0QRqESNwt8UPKTpM19M2HUqOoCYX4n865qhVkjMr2yRjK9u+HtdKZnoDRbT3o/ogSGxkctqMJmSQcgg8UdowwlAIEktIGMwk6dsAt4yYfLWABsLRulNr9SRUkTE6eNdheQaBpdD7BgIwzkEJ5cHFrd8Z9s+yRdX2RG2uXjQ3JmxdfVS2w4sboSurCQyjhbZ198Pt0/gTToinxD/BxR4rS/xyHy1o4JRbeuY103iOqGXqL1ZmoapTEA0dJ4/S51qC+xFj2KbOj555mTFG/ubWKA3FG6lezYsWlwTFPJgCQPmMu4B3dW+8ASri9aDtFs9Zt7Ul6VcE/znu/PVUPgAZTvAntb9ZYn7LK801nhIc4AAJ5mAxr1qVhtJ05QxuC6vU4c4F8mhi4YlaMDQTk4/5U0I1btn1rR7sgz9yiiEvBBV6Dha7UrDOOqoN6eXL9KE5atUcsuN/kieejj46KmLzJcl4eoElxyb2pJj+LCLzwqoAjs/BLzNWGX1fLWO2xHUPB3tDP5m3PKp9aPv55KRXp/3H3wCHH9GxIzzA1oBX3Gb5GzoW3X1CInpeaNoqs6UqYuzUozl3068o4gdCypigh0OYDwpGzQXrWOhKMP8rdM="

notifications:
  email:
    recipients:
      - millian.poquet@gmail.com
    on_success: change
    on_failure: always

sudo: required
dist: trusty

before_install:
  - export BATSIM_BASE_DIR=$(pwd)

  # SSH setup in order to publish doxygen documentation on the Inria gforge
  - cd travis # SSH setup for sharing the doxygen documentation
  - openssl aes-256-cbc -k "$ssh_key_password" -in travisci_rsa.enc -out travisci_rsa -d
  - chmod 0600 travisci_rsa
  - cp travisci_rsa ~/.ssh/id_rsa
  - ssh-keyscan scm.gforge.inria.fr >> ~/.ssh/known_hosts

  # Update apt lists
  - cat /etc/apt/sources.list
  - cp /etc/apt/sources.list /tmp/sources.list
  - echo 'deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - echo 'deb-src http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - sudo mv /tmp/sources.list /etc/apt/sources.list

  # Install boost
  - cd /tmp
  - sudo apt-get update
  - sudo apt-get build-dep libboost-all-dev
  - sudo apt-get -b source -t xenial libboost-all-dev
  - sudo ls -l .
  - sudo dpkg --force-all -i libboost*.deb
  - find /usr -name 'libboost*.so*'

install:
  # Install SimGrid
  - cd ${BATSIM_BASE_DIR}
  - git clone https://github.com/oar-team/simgrid-batsim.git -b batsim-compatible --depth 1 simgrid-batsim
  - cd simgrid-batsim
  - mkdir build
  - cd build
  - cmake .. -Denable_documentation=OFF
  - make -j $(nproc)
  - sudo make install

  # Install rapidjson
  - cd ${BATSIM_BASE_DIR}
  - git clone https://github.com/miloyip/rapidjson.git
  - cd rapidjson
  - git checkout 3d5848a # v1.02
  - sudo cp -a include/rapidjson /usr/include

  # Install redox
  - cd ${BATSIM_BASE_DIR}
  - git clone https://github.com/hmartiro/redox.git
  - cd redox
  - git checkout 64becf28f3dd
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install
  - make -j $(nproc)
  - make install
  - cd ../install
  - mv -f lib64 lib
  - sudo cp -r ./* /usr/

  ####################
  # Python libraries #
  ####################
  # Upgrade pip
  - pip install --user --upgrade pip

  # Install Execo (used in the test script)
  - cd ${BATSIM_BASE_DIR}
  - git clone https://github.com/mickours/execo.git
  - cd execo
  - git checkout 725fddc # cwd support
  - pip install --user -U -e .

  # Install redis (used by pybatsim)
  - pip install --user -U redis

  # Install sortedcontainers (used in some schedulers, used by the tests)
  - pip install --user -U sortedcontainers

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Build steps
script:
  ################
  # Build Batsim #
  ################
  - cd ${BATSIM_BASE_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make -j $(nproc)
  - sudo make install

  #########################
  # Doxygen documentation #
  #########################
  - cd ${BATSIM_BASE_DIR}/doc
  - doxygen
  - cat doxygen_warnings.log
  - eval "[ $(wc -c doxygen_warnings.log | cut -d ' ' -f1) -eq 0 ]" # Fails on warnings -> travis stops
  - rsync -rlgoDz --delete doxygen_doc/html/ mpoquet@scm.gforge.inria.fr:/home/groups/batsim/htdocs

  #########
  # Tests #
  #########
  # Let's run the redis server
  - |
    redis-server>/dev/null &
    while ! nc -z localhost 6379; do
      sleep 1
    done

  # Let's run the tests
  - cd ${BATSIM_BASE_DIR}
  - bash -ex ./test/run_tests.sh
