# Dependencies
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-all-dev

sudo: required
install:
  - git clone https://mpoquet@github.com/oar-team/simgrid-batsim.git -b batsim-compatible --depth 1 simgrid-batsim
  - cd simgrid-batsim
  - mkdir build
  - cd build
  - cmake .. -Denable_documentation=OFF
  - make -j 4
  - sudo make install

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
