# Dependencies
addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libboost-all-dev

sudo: required
dist: trusty

before_install:
  - export BATSIM_BASE_DIR=$(pwd)

install:
  - cd ${BATSIM_BASE_DIR}
  - git clone https://mpoquet@github.com/oar-team/simgrid-batsim.git -b batsim-compatible --depth 1 simgrid-batsim
  - cd simgrid-batsim
  - mkdir build
  - cd build
  - cmake .. -Denable_documentation=OFF
  - make -j $(nproc)
  - sudo make install

  - cd ${BATSIM_BASE_DIR}
  - git clone https://github.com/miloyip/rapidjson.git
  - cd rapidjson
  - git checkout 3d5848a # v1.02
  - sudo cp -a include/rapidjson /usr/include

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang

# Build steps
script:
  - cd ${BATSIM_BASE_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make -j $(nproc)
  - cd ..
