# Dependencies
addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libboost-all-dev
      - doxygen
      - graphviz

sudo: required
dist: trusty

before_install:
  - export BATSIM_BASE_DIR=$(pwd)

  - cd travis
  - openssl aes-256-cbc -K $encrypted_3cfa041ed9d5_key -iv $encrypted_3cfa041ed9d5_iv -in travisci_rsa.enc -out travisci_rsa -d
  - chmod 0600 travisci_rsa
  - cp travisci_rsa ~/.ssh/id_rsa

install:
  - cd ${BATSIM_BASE_DIR} # Install SimGrid
  - git clone https://mpoquet@github.com/oar-team/simgrid-batsim.git -b batsim-compatible --depth 1 simgrid-batsim
  - cd simgrid-batsim
  - mkdir build
  - cd build
  - cmake .. -Denable_documentation=OFF
  - make -j $(nproc)
  - sudo make install

  - cd ${BATSIM_BASE_DIR} # Install rapidjson
  - git clone https://github.com/miloyip/rapidjson.git
  - cd rapidjson
  - git checkout 3d5848a # v1.02
  - sudo cp -a include/rapidjson /usr/include

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang

# Build steps
script:
  - cd ${BATSIM_BASE_DIR} # Compile Batsim
  - mkdir build
  - cd build
  - cmake ..
  - make -j $(nproc)

  - cd ${BATSIM_BASE_DIR}/doc # Doxygen documentation
  - doxygen
  - cat doxygen_warnings.log
  - eval "[ $(wc -c doxygen_warnings.log | cut -d ' ' -f1) -eq 0 ]" # Stops travis on doxygen warnings
  - rsync -rlgoDvz doxygen_doc/html/ mpoquet@scm.gforge.inria.fr:/home/groups/batsim/htdocs
