# Dependencies
addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libboost-all-dev
      - doxygen
      - graphviz
      - python-pip
env:
  global:
    secure: "ayxHlRpg3qX84ZkiLVd5s78/woUyNET99uNFviUzdDiQ9iUoaudYuu9uG9zi0RVfY0QRqESNwt8UPKTpM19M2HUqOoCYX4n865qhVkjMr2yRjK9u+HtdKZnoDRbT3o/ogSGxkctqMJmSQcgg8UdowwlAIEktIGMwk6dsAt4yYfLWABsLRulNr9SRUkTE6eNdheQaBpdD7BgIwzkEJ5cHFrd8Z9s+yRdX2RG2uXjQ3JmxdfVS2w4sboSurCQyjhbZ198Pt0/gTToinxD/BxR4rS/xyHy1o4JRbeuY103iOqGXqL1ZmoapTEA0dJ4/S51qC+xFj2KbOj555mTFG/ubWKA3FG6lezYsWlwTFPJgCQPmMu4B3dW+8ASri9aDtFs9Zt7Ul6VcE/znu/PVUPgAZTvAntb9ZYn7LK801nhIc4AAJ5mAxr1qVhtJ05QxuC6vU4c4F8mhi4YlaMDQTk4/5U0I1btn1rR7sgz9yiiEvBBV6Dha7UrDOOqoN6eXL9KE5atUcsuN/kieejj46KmLzJcl4eoElxyb2pJj+LCLzwqoAjs/BLzNWGX1fLWO2xHUPB3tDP5m3PKp9aPv55KRXp/3H3wCHH9GxIzzA1oBX3Gb5GzoW3X1CInpeaNoqs6UqYuzUozl3068o4gdCypigh0OYDwpGzQXrWOhKMP8rdM="

notifications:
  email:
    recipients:
      - millian.poquet@gmail.com
    on_success: change
    on_failure: always

sudo: required
dist: trusty

before_install:
  - export BATSIM_BASE_DIR=$(pwd)

  # SSH setup in order to publish doxygen documentation on the Inria gforge
  - cd travis # SSH setup for sharing the doxygen documentation
  - openssl aes-256-cbc -k "$ssh_key_password" -in travisci_rsa.enc -out travisci_rsa -d
  - chmod 0600 travisci_rsa
  - cp travisci_rsa ~/.ssh/id_rsa
  - ssh-keyscan scm.gforge.inria.fr >> ~/.ssh/known_hosts

install:
  # Install SimGrid
  - cd ${BATSIM_BASE_DIR}
  - git clone https://mpoquet@github.com/oar-team/simgrid-batsim.git -b batsim-compatible --depth 1 simgrid-batsim
  - cd simgrid-batsim
  - mkdir build
  - cd build
  - cmake .. -Denable_documentation=OFF
  - make -j $(nproc)
  - sudo make install

  # Install rapidjson
  - cd ${BATSIM_BASE_DIR}
  - git clone https://github.com/miloyip/rapidjson.git
  - cd rapidjson
  - git checkout 3d5848a # v1.02
  - sudo cp -a include/rapidjson /usr/include

  ####################
  # Python libraries #
  ####################
  # Upgrade pip
  - pip install --user --upgrade pip

  # Install Execo (used in the test script)
  - cd ${BATSIM_BASE_DIR}
  - git clone https://github.com/mickours/execo.git
  - cd execo
  - git checkout 725fddc # cwd support
  - pip install --user -U -e .

  # Install sortedcontainers (used in some schedulers, used by the tests)
  - pip install --user -U sortedcontainers

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Build steps
script:
  ################
  # Build Batsim #
  ################
  - cd ${BATSIM_BASE_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make -j $(nproc)
  - sudo make install

  #########################
  # Doxygen documentation #
  #########################
  - cd ${BATSIM_BASE_DIR}/doc
  - doxygen
  - cat doxygen_warnings.log
  - eval "[ $(wc -c doxygen_warnings.log | cut -d ' ' -f1) -eq 0 ]" # Fails on warnings -> travis stops
  - rsync -rlgoDz --delete doxygen_doc/html/ mpoquet@scm.gforge.inria.fr:/home/groups/batsim/htdocs

  #########
  # Tests #
  #########
  # Let's make sure the our scripts' examples work correctly
  - cd ${BATSIM_BASE_DIR}
  - ./tools/experiments/execute_one_instance.py ./tools/experiments/instance_examples/pybatsim_filler_tiny.yaml

  - cd ${BATSIM_BASE_DIR}
  - ./tools/experiments/execute_one_instance.py ./tools/experiments/instance_examples/pybatsim_filler_medium.yaml

  - cd ${BATSIM_BASE_DIR}
  - ./tools/experiments/execute_instances.py ./tools/experiments/instances_examples/pyfiller_tiny_medium_mixed.yaml

  # Let's run the tests
  - cd ${BATSIM_BASE_DIR}
  - bash -ex ./test/run_tests.sh
